# Generated by Django 4.1.5 on 2023-02-08 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipping_address', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='postalCOde',
            new_name='postalCode',
        ),
    ]
