# Generated by Django 4.1.5 on 2023-02-09 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_order_paidat_alter_order_deliveredat'),
        ('shipping_address', '0002_rename_postalcode_shippingaddress_postalcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipping_address', to='order.order'),
        ),
    ]
