# Generated by Django 4.1.5 on 2023-02-08 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_item', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='Product',
            new_name='product',
        ),
    ]
