# Generated by Django 4.1.5 on 2023-02-08 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='PaidAt',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
