# Generated by Django 4.1.5 on 2023-02-08 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_paidat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='PaidAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='deliveredAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
