# Generated by Django 4.1.5 on 2023-02-09 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_order_paidat_alter_order_deliveredat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='Product',
        ),
    ]
