# Generated by Django 4.1.5 on 2023-02-09 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_order_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='PaidAt',
            new_name='paidAt',
        ),
    ]
